[New Utility] Workflow to rename FASTQ files (non-destructive)
theiagen/public_health_bioinformatics pull request #267
Opened 2023-12-13 17:43 UTC by cimendes

Closes #266

## :hammer_and_wrench: Changes Being Made

This PR implements a new utility workflow as requested in #266. This workflow received a read file or a pair of read files (FASTQ), compressed or uncompressed, and returned a new, renamed and compressed FASTQ file for submission in GISAID. 

### Impacted Workflows/Tasks

None, this is a new implementation

## :brain: Context and Rationale

Requested by SFPHL

## :clipboard: Workflow/Task Steps

This is a sample-level workflow. If a reverse read (`read2`) is provided, the files get renamed to the provided `new_filename` input with the notation `<new_filename>_R1.fastq.gz` and `<new_filename>_R2.fastq.gz`. If only `read1` is provided, the file gets renamed to `<new_filename>.fastq.gz`. If a not-compressed file is provided, this gets compressed automatically by the workflow. ´

### Inputs

```
  input {
    File read1  
    File? read2
    String new_filename
  }
```

`read1`: Mandatory input; Forward-facing or single-end reads, compressed or uncompressed
`read2`: Optional input; Reverse-facing reads, compressed or uncompressed
`new_filename`: Mandatory input; String with new name for read files

### Outputs

```
output {
    String rename_fastq_files_version = version_capture.phb_version
    String rename_fastq_files_analysis_date = version_capture.date
    File read1_renamed = select_first([rename_PE_files.read1_renamed, rename_SE_files.read1_renamed])
    File? read2_renamed = rename_PE_files.read2_renamed
  }
```

`rename_fastq_files_version`: version of PHB used to run this workflow
`rename_fastq_files_analysis_date`: date of renaming
`read1_renamed`: Forward-facing or single-end reads. Always present
`read2_renamed`: Reverse-facing reads. Only present if `read2` is provided

### Impacted Outputs

None, new workflow

## :test_tube: Testing

### Locally

Paired-end reads (compressed):
<img width="686" alt="image" src="https://github.com/theiagen/public_health_bioinformatics/assets/15690332/937e5941-ce56-444a-892f-961344f66cbe">

Single-end reads (compressed):
<img width="685" alt="image" src="https://github.com/theiagen/public_health_bioinformatics/assets/15690332/303dd562-4e44-469c-ba91-1b631d6df190">

Single-end reads (uncompressed):
<img width="690" alt="image" src="https://github.com/theiagen/public_health_bioinformatics/assets/15690332/97519590-ef74-442b-9ff8-9ba87efd1a35">

### Terra

Underway

### Scenarios for Reviewer to Test

- Weird filenames
- Should we keep the `_R1.fastq.gz` output name or change it to something else?

## :microscope: Quality checks

Pull Request (PR) checklist:
- [x] Include a description of what is in this pull request in this message.
- [ ] The workflow/task has been tested locally and on Terra
- [ ] The CI/CD has been adjusted and tests are passing
- [x] Everything follows the [style guide](https://theiagen.notion.site/Style-Guide-WDL-Workflow-Development-bb456f34322d4f4db699d4029050481c)

2023-12-14 19:50 UTC, emily-smith1 approved these changes
Tested **successfully** on 10 single-end and 10 paired-end SARS-CoV-2 read files in the renaming_test table in [this Terra workspace](https://app.terra.bio/#workspaces/cdph-terrabio-taborda-manual/CDPH_Smith_Sandbox/data). Files were renamed according to corresponding GISAID accession per the original request.

2023-12-18 14:12 UTC, sage-wright commented on tasks/utilities/task_rename_files.wdl
> +  command <<<
do we need to have two separate tasks for this? the way the PE  task is set up looks like we shouldn't need the SE task?

2023-12-18 14:15 UTC, sage-wright requested changes
Looks good, but would drop the single end version, since r2 is already optional and you're checking for its existence in the PE version of the task anyways.

2023-12-18 16:31 UTC, cimendes commented
> Looks good, but would drop the single end version, since r2 is already optional and you're checking for its existence in the PE version of the task anyways.

The reason why I introduced the SE task was because I couldn't find a smart way to have the output be *.fastq.gz or *_1.fastq.gz for the forward read... Maybe we can think of something smart together? :)

2023-12-20 19:12 UTC, merged