[Snippy_Variants and Snippy_Streamline] Accept assembly_fasta as input
theiagen/public_health_bioinformatics pull request #569
Opened 2024-08-01 09:23 UTC by cimendes

…input

This PR closes #568

🗑️ This dev branch should <NOT> be deleted after merging to main.

## :brain: Summary

## :zap: Impacted Workflows/Tasks

This PR may lead to different results in pre-existing outputs: **Yes/No**

This PR uses an element that could cause duplicate runs to have different results: **Yes/No**

## :hammer_and_wrench: Changes

### :gear: Algorithm

### ➡️ Inputs

### ⬅️ Outputs

## :test_tube: Testing

### Suggested Scenarios for Reviewer to Test

## :microscope: Final Developer Checklist

- [ ] The workflow/task has been tested and results, including file contents, are as anticipated
- [ ] The CI/CD has been adjusted and tests are passing (Theiagen developers)
- [ ] Code changes follow the [style guide](https://theiagen.notion.site/Style-Guide-WDL-Workflow-Development-51b66a47dde54c798f35d673fff80249)
- [ ] Documentation and/or workflow diagrams have been updated if applicable (Theiagen developers only)

## 🎯 Reviewer Checklist

- [ ] All changed results have been confirmed
- [ ] You have tested the PR appropriately (see the [testing guide](https://theiagen.notion.site/PR-Testing-Guide-Determining-Appropriate-Levels-of-Testing-4764e98a6aeb460185039c0896714590) for more information)
- [ ] All code adheres to the [style guide](https://theiagen.notion.site/Style-Guide-WDL-Workflow-Development-51b66a47dde54c798f35d673fff80249)
- [ ] MD5 sums have been updated
- [ ] The PR author has addressed all comments
- [ ] The documentation has been updated

2024-08-21 09:53 UTC, cimendes commented
@sage-wright documentation has been updated

2024-08-22 11:31 UTC, sage-wright commented on workflows/phylogenetics/wf_snippy_streamline_fasta.wdl
> +    String tree_name_updated = sub(tree_name, " ", "_")
Can you move this out of the input section to the line beneath it so it doesn't show up on Terra?

2024-08-22 11:33 UTC, sage-wright requested changes
Looks great, just one minor modification requested to prevent the tree name updated from showing up on Terra -- should have no functional issues.

2024-08-22 12:40 UTC, cimendes commented
I've moved the tree_name_updated from the input block on snippy_streamline_fasta and snippy_tree
![image](https://github.com/user-attachments/assets/05b37e5e-3224-4a1b-a26f-314ebf3dd17c)

2024-08-22 14:21 UTC, sage-wright approved these changes
wonderful

2024-08-22 14:22 UTC, merged