[TheiaCoV] Split database from Kraken2_TheiaCoV task
theiagen/public_health_bioinformatics pull request #670
Opened 2024-11-07 09:53 UTC by cimendes

This PR closes #563, closes #520

🗑️ This dev branch should <NOT> be deleted after merging to main.

## :brain: Summary

This PR addresses several issues that came up when the RSV target organism was set differently for RSV-A and RSV-B, i.e. `rsv_a_kraken_target_organism = "Respiratory syncytial virus"` and `rsv_b_kraken_target_organism = "Human orthopneumovirus"` due to the use of an old database. As the existing docker image had an embedded database, it meant that each time the Kraken database would need to be updated, it would have to be done inside the docker container, which would not be efficient. 

This PR simply updates the existing `kraken2_theiacov` task to split the database from the container. The new database is custom built with human + refseq viral sequences as of 2024-08-28.

No inputs or outputs have been altered other than what is strictly required to make the new code changes functional.

Behaviour change:
- the percentage of sc2 is now only reported for TheiaCoV is the target organism is indeed SC2. To account for this the output type has been changed from Float to String.
- Freyja now has a kraken2_target_organism input that by default is SC2, but is user modifyable

## :zap: Impacted Workflows/Tasks

Impacted tasks
- kraken2_theiacov
- kraken2_parse_classified

Impacted workflows
- TheiaCoV
  - Illumina_PE
  - Illumina_SE
  - Clearlabs
  - ONT
- Freyja_FASTQ
- NCBI_Scrub
  - SE
  - PE 

This PR may lead to different results in pre-existing outputs: **Yes**
- Use of an updated database may reflect changes in how taxa are identified.

This PR uses an element that could cause duplicate runs to have different results: **No**

## :hammer_and_wrench: Changes

### :gear: Algorithm

As explained above, the only change in algorithm is that the percentage of sc2 is now only reported if the target organism is SC2, otherwise this column is blank. To accomplish this the data type has been changed from Float to String. Impacts column sorting as it is now alpha-numeric.

### ➡️ Inputs

freyja_fastq new input:
- kraken2_target_organism

### ⬅️ Outputs

Percent sc2 is now a string output, rather than a float output

## :test_tube: Testing

### Suggested Scenarios for Reviewer to Test

## :microscope: Final Developer Checklist

- [ ] The workflow/task has been tested and results, including file contents, are as anticipated
- [ ] The CI/CD has been adjusted and tests are passing (Theiagen developers)
- [ ] Code changes follow the [style guide](https://theiagen.notion.site/Style-Guide-WDL-Workflow-Development-51b66a47dde54c798f35d673fff80249)
- [ ] Documentation and/or workflow diagrams have been updated if applicable (Theiagen developers only)

## 🎯 Reviewer Checklist

- [ ] All changed results have been confirmed
- [ ] You have tested the PR appropriately (see the [testing guide](https://theiagen.notion.site/PR-Testing-Guide-Determining-Appropriate-Levels-of-Testing-4764e98a6aeb460185039c0896714590) for more information)
- [ ] All code adheres to the [style guide](https://theiagen.notion.site/Style-Guide-WDL-Workflow-Development-51b66a47dde54c798f35d673fff80249)
- [ ] MD5 sums have been updated
- [ ] The PR author has addressed all comments
- [ ] The documentation has been updated

2024-11-25 15:42 UTC, Michal-Babins commented on workflows/theiacov/updates/wf_ncbi_scrub_pe.wdl
> +      target_organism = "Severe acute respiratory syndrome coronavirus 2"
For NCBI scrub workflows can we set this to be a workflow input and not hard coded on the task level?

2024-11-25 15:45 UTC, Michal-Babins requested changes
For ncbi scrubber, please pass in workflow level variable and do not hard code on task level.

2024-11-25 15:45 UTC, Michal-Babins commented on workflows/theiacov/updates/wf_ncbi_scrub_se.wdl
> +      target_organism = "Severe acute respiratory syndrome coronavirus 2"
Same here for workflow level input

2024-11-25 15:51 UTC, Michal-Babins commented
Testing illumina PE [here](https://app.terra.bio/#workspaces/cdph-terrabio-taborda-manual/CDPH_Bioinformatics_Development/job_history/58507ee8-c048-4129-b482-f01e6cceeb12) for WNV, MPox, Flu, Sars-Cov-2.

2024-11-25 18:23 UTC, Michal-Babins commented
Everything looks good in the test and the output is properly identified by kraken from what we would expect. One of the flu samples returned nothing from kraken, but I ran it against PHBv2.2.1 and it was the same thing so something with that sample is just slightly off. 

Run with isolated sample [here](https://app.terra.bio/#workspaces/cdph-terrabio-taborda-manual/CDPH_Bioinformatics_Development/job_history/1fe43e1f-03a0-4780-8e56-9a77138b01a0)

2024-12-05 10:09 UTC, cimendes commented
@Michal-Babins I've exposed the required input parameter, as requested! A little merge conflict has been solved and the CI has been updated.

2024-12-05 10:27 UTC, cimendes commented
Ops, forgot about the docs update! Now everything is done!

2024-12-05 14:18 UTC, Michal-Babins approved these changes
Specified at the higher level now, looks good to me. Thank you.

2024-12-05 14:40 UTC, merged