[Clair3_Variants] Clair3_Variants_ONT_PHB workflow
theiagen/public_health_bioinformatics pull request #708
Opened 2024-12-31 00:18 UTC by Michal-Babins

This PR closes #707

🗑️ This dev branch should <NOT> be deleted after merging to main.

## :brain: Summary

Here we introduce the Clair3_Variants_ONT_PHB MVP workflow designed to work with ONT data and various chemistries. The workflow aligns ONT reads to a reference genome using minimap2 with long-read specific settings. The aligned reads are then processed into a sorted BAM file with it's index, which are required for variant calling with clair3. We also perform an indexing operation using `samtools faidx` to index the reference, also required by Clair3. Clair3 performs the variant calling with settings defaulted for haploid organisms, though these can be adjusted for diploid analysis (rare). The workflow produces multiple VCF files including a final merged VCF containing the high-confidence variant calls, along with intermediate files from both pileup and full-alignment approaches. 

## :zap: Impacted Workflows/Tasks

Workflows:
- Clair3_Variants_ONT (new)
- TheiaMeta_Illumina_PHB
- Freyja_Fastq_PHB
Task:
- task_clair3_variants (new)
- samtools_faidx  (new)
- task_minimap2

This PR may lead to different results in pre-existing outputs: **No**

This PR uses an element that could cause duplicate runs to have different results: **No**

## :hammer_and_wrench: Changes

- Adds new workflow Clair3_Variants_ONT to standalone workflows
- Adds new task clair3_variants
- Creates new task samtools_faidx for indexing fasta
- Adds `long_read_flags` Boolean to minimap to handle long read specific formatting in sam / bam formats. If set to true the following flags are set -L --cs --MD. 
- Updates Freyja_Fastq and ThieaMeta_Illumina minimap2 tasks and sets `long_read_flags = `false` so those options do not get exposed for the tasks. 
- Add new documentation for `Clair3_Variants`
- Adds new docker image to theiagen builds: `us-docker.pkg.dev/general-theiagen/theiagen/clair3-extra-models:1.0.10`

NOTE: Docker build uses staphb docker as base, but adds models from [here](https://github.com/nanoporetech/rerio) deemed latest. Does not download deprecated model configurations. 

### :gear: Algorithm

Clair3_variants_ont takes the following approach:
1. Reads are aligned to a reference genome using minimap2 in `ont` mode with specific long-read flags (-L --cs --MD) to handle long CIGAR strings and provide detailed alignment information.
2. The resulting SAM file is converted to BAM format, sorted, and indexed using samtools, while simultaneously the reference genome is indexed with samtools faidx.
3. Clair3 performs variant calling using these prepared files, with default settings optimized for haploid genomes (disable_phasing=true, enable_haploid_precise=true, include_all_contigs=true).
4. Variants are called using two approaches: a pileup-based approach for high-confidence regions and a full-alignment approach for more complex regions, which are then merged into a final VCF.
5. The workflow generates multiple output VCF files (pileup, full-alignment, and merged final), with an optional gvcf output that includes non-variant sites, while maintaining version tracking throughout all steps.

### ➡️ Inputs

```
File read1
File reference_genome_file
String samplename
String? clair3_model
String? clair3_docker
Int? clair3_memory
Int? clair3_cpu
Int? clair3_disk_size
Int? clair3_variant_quality
Boolean? clair3_include_all_contigs
Boolean? clair3_enable_haploid_precise
Boolean? clair3_disable_phasing
Boolean? clair3_enable_gvcf
Boolean? clair3_enable_long_indel
```

### ⬅️ Outputs

```
String samtools_version = sam_to_sorted_bam.samtools_version
File aligned_bam = sam_to_sorted_bam.bam
File aligned_bai = sam_to_sorted_bam.bai
# Data handling - Reference genome - samtools version
File aligned_fai = samtools_faidx.fai
#Clair3 variant calling
String clair3_variants_wf_version = version_capture.phb_version
String clair3_version = clair3_variants.clair3_version
File clair3_variants_final_vcf = clair3_variants.clair3_variants_final_vcf
File clair3_variants_pileup_vcf = clair3_variants.clair3_variants_pileup_vcf
File clair3_variants_full_alignment_vcf = clair3_variants.clair3_variants_full_alignment_vcf
File? clair3_variants_gvcf = clair3_variants.clair3_variants_gvcf
String clair3_docker_image = clair3_variants.clair3_variants_docker_image
String clair3_model_used = clair3_variants.clair3_model_used
```

## :test_tube: Testing

Tested against dataset from this [paper](https://elifesciences.org/reviewed-preprints/98300) minus 4 who didn't have a reference. Test found [here](https://app.terra.bio/#workspaces/theiagen-training-workspaces/Theiagen_Babinski_Sandbox/job_history/08ca6d4c-8454-40c8-a7f0-6406472c8d13)
Test against a few [A. fumagatis ont](https://app.terra.bio/#workspaces/theiagen-training-workspaces/Theiagen_Babinski_Sandbox/job_history/5024dc84-c611-446e-b20a-129080a5e5cb)
Test with clair3 model set to [ont](https://app.terra.bio/#workspaces/theiagen-training-workspaces/Theiagen_Babinski_Sandbox/job_history/1feb444c-9a25-4b93-b774-5367d2c2805d)
Test with clair3 model set to [ont_guppy2](https://app.terra.bio/#workspaces/theiagen-training-workspaces/Theiagen_Babinski_Sandbox/job_history/66608f3b-ecf1-4977-8e35-0e2bc61af8a8)
Test with clair3 model set to [ont_guppy5](https://app.terra.bio/#workspaces/theiagen-training-workspaces/Theiagen_Babinski_Sandbox/job_history/7fdb5624-7732-498f-aa53-891e59ff38a3)
Test with clair3 model set to [r941_prom_sup_g5014](https://app.terra.bio/#workspaces/theiagen-training-workspaces/Theiagen_Babinski_Sandbox/job_history/a928ac71-800e-4090-a2d2-d8a687a94b8e)
Test with clair3 model set to [r941_prom_hac_g360+g422](https://app.terra.bio/#workspaces/theiagen-training-workspaces/Theiagen_Babinski_Sandbox/job_history/47137e18-b095-4cc3-9dda-5fbbff3739a2)
Test with clair3 model set to [r941_prom_hac_g238](https://app.terra.bio/#workspaces/theiagen-training-workspaces/Theiagen_Babinski_Sandbox/job_history/8e0dcd4a-f31b-4ca4-a428-a08b194f72c3)
Test with clair3 model set to [r1041_e82_400bps_sup_v500](https://app.terra.bio/#workspaces/theiagen-training-workspaces/Theiagen_Babinski_Sandbox/job_history/88e00a55-016f-4478-a80f-bf70ab272ed9)
Test with clair3 model set to [r1041_e82_400bps_hac_v500](https://app.terra.bio/#workspaces/theiagen-training-workspaces/Theiagen_Babinski_Sandbox/job_history/db37a437-ada0-403a-b79e-4467d3e843f1)
Test with clair3 model set to [r1041_e82_400bps_sup_v410](https://app.terra.bio/#workspaces/theiagen-training-workspaces/Theiagen_Babinski_Sandbox/job_history/baeb6c03-24df-40aa-8cb3-7d8b788b19b4)
Test with clair3 model set to [r1041_e82_400bps_hac_v410](https://app.terra.bio/#workspaces/theiagen-training-workspaces/Theiagen_Babinski_Sandbox/job_history/3c387d55-1133-4056-bf55-74c197a91d7e)
Test with [diploid settings](https://app.terra.bio/#workspaces/theiagen-training-workspaces/Theiagen_Babinski_Sandbox/job_history/644c3a68-979a-48c8-b107-e23ea110f4e1), note that diploid settings will only work with reference that has chromosomes specified in the header, see [test expected to fail](https://app.terra.bio/#workspaces/theiagen-training-workspaces/Theiagen_Babinski_Sandbox/job_history/a6c9c1bc-1990-439e-b71a-0bcdb48ecacb). Non-human should always use `--include-all-ctgs` flag. 
Test with [gvcf enabled](https://app.terra.bio/#workspaces/theiagen-training-workspaces/Theiagen_Babinski_Sandbox/job_history/1e835239-8d33-45c3-a7b4-476db284fa9e)
Test with [long indels enabled](https://app.terra.bio/#workspaces/theiagen-training-workspaces/Theiagen_Babinski_Sandbox/job_history/5690b5ef-a720-49b5-b149-3299856d71ae)
Test [TheiaMeta_Illumina_PE](https://app.terra.bio/#workspaces/theiagen-training-workspaces/Theiagen_Babinski_Sandbox/job_history/016f4cf7-9345-424b-bd0f-a391d30bf072) to make sure minimap2 update works as expected.

Need to test freyja with ont data that is valid. 

### Suggested Scenarios for Reviewer to Test

Test with the `clair3_combined` datadable, not all but some. Any ont data with a reference is valid to test. Test [...]

2025-01-21 09:59 UTC, cimendes requested changes
Went through the code and everything is looking very good! I just have a few comments that need your attention @Michal-Babins! Congratulations on top-notch work!

2025-01-21 09:59 UTC, cimendes commented on docs/workflows/phylogenetic_construction/clair3_variants.md
> +PHB `Clair3_Variants` also supports 10 model configuration for `clair3` ONT:
i would remove the "also" from this phrase

2025-01-21 09:59 UTC, cimendes commented on docs/workflows/phylogenetic_construction/clair3_variants.md
> +| clair3_variants_ont | **clair3_disable_phasing** | Boolean | Disable whatshap phasing | true | Optional |
Not a comment, but I read this as WhatsApp and was confused 🤣

2025-01-21 09:59 UTC, cimendes commented on docs/workflows/phylogenetic_construction/clair3_variants.md
> +
Could you please add a workflow diagram here? Can be something really simple! You already have it on the design doc 😸

2025-01-21 09:59 UTC, cimendes commented on docs/workflows/phylogenetic_construction/clair3_variants.md
> +!!! warning "Note on Haploid Settings"
I would move this section to above the table for more awareness! We have some users who are running diploid organisms in our workflows and this message is important to them!

2025-01-21 09:59 UTC, cimendes commented on docs/workflows/phylogenetic_construction/clair3_variants.md
> +!!! warning "Note on VCF Outputs"
I would also move this warning to above the table for more awareness!

2025-01-21 09:59 UTC, cimendes commented on docs/workflows/phylogenetic_construction/clair3_variants.md
> +| [Phylogenetic Construction](../../workflows_overview/workflows_type.md/#phylogenetic-construction) | [Bacteria](../../workflows_overview/workflows_kingdom.md/#bacteria), [Mycotics](../../workflows_
I think it needs to be vX.X.X for easy find and replace

2025-01-21 09:59 UTC, cimendes commented on docs/workflows_overview/workflows_alphabetically.md
> +| [**Clair3_Variants**](../workflows/phylogenetic_construction/clair3_variants.md)| ONT Variant Caller | Any taxa | Sample-level | Yes | 2.3.0 | [Clair3_Variants_ONT_PHB](https://dockstore.org/workfl
vX.X.X here for easy find and replace

2025-01-21 09:59 UTC, cimendes commented on docs/workflows_overview/workflows_kingdom.md
> +| [**Clair3_Variants**](../workflows/phylogenetic_construction/clair3_variants.md)| ONT Variant Caller | Any taxa | Sample-level | Yes | 2.3.0 | [Clair3_Variants_ONT_PHB](https://dockstore.org/workfl
vX.X.X here for easy find and replace!

2025-01-21 09:59 UTC, cimendes commented on docs/workflows_overview/workflows_type.md
> +| [**Clair3_Variants**](../workflows/phylogenetic_construction/clair3_variants.md)| ONT Variant Caller | Any taxa | Sample-level | Yes | 2.3.0 | [Clair3_Variants_ONT_PHB](https://dockstore.org/workfl
vX.X.X here for easy find and replace!

2025-01-21 09:59 UTC, cimendes commented on tasks/alignment/task_minimap2.wdl
> +      ~{true="-L --cs --MD" false="" long_read_flags} \
fantastic addition! makes using this task on other workflows much much easier!

2025-01-21 09:59 UTC, cimendes commented on tasks/gene_typing/variant_detection/task_clair3_variants.wdl
> +    # Make sure alignment bam file and fasta index are localized
nice debugging information! 🌟

2025-01-21 09:59 UTC, cimendes commented on tasks/gene_typing/variant_detection/task_clair3_variants.wdl
> +    cp ~{reference_genome_file} ~{ref_basename}
WDL being WDL makes me sad!

2025-01-21 09:59 UTC, cimendes commented on tasks/gene_typing/variant_detection/task_clair3_variants.wdl
> +    String clair3_model_used = clair3_model
great call on exposing the model used! 🌟

2025-01-21 09:59 UTC, cimendes commented on tasks/utilities/data_handling/task_fasta_utilities.wdl
> +    maxRetries: 0
just a warning that maxRetries is set to 0 here. It should be fine 99% of the time but Terra/Cromwell might have a momentary moment that can be resolved with a retry. I would change this to 3.

2025-01-21 09:59 UTC, cimendes commented on workflows/freyja/wf_freyja_fastq.wdl
> +        long_read_flags = false
Hummmmmmmm I understand that this is out of scope for this PR and it's not a request that I'm making, just writing down potential downstream consequences. We should adjust Freyja to use the long-read flags if ONT is `true`. I'll make an issue upon merging of this PR. This is fine right now to not impact Freyja with unforeseen changes.

2025-01-21 09:59 UTC, cimendes commented on workflows/standalone_modules/wf_clair3_variants_ont.wdl
> +  }
version_capture outputs are not captured. This is making version_capture upset! 💔

2025-01-21 10:00 UTC, cimendes commented
Also, merge conflict alert! ⚠️ 😄

2025-01-21 14:13 UTC, cimendes commented on workflows/standalone_modules/wf_clair3_variants_ont.wdl
> +  }
I am blind!!! I did not see!!! Blame my old age!

2025-01-21 14:17 UTC, Michal-Babins commented on workflows/freyja/wf_freyja_fastq.wdl
> +        long_read_flags = false
Yeah, I saw this too, but didn't want to impact everything outside of clair3 scope. But agree that this should be another issue with it's own testing.

2025-01-21 14:58 UTC, Michal-Babins commented on tasks/utilities/data_handling/task_fasta_utilities.wdl
> +    maxRetries: 0
Good catch.

2025-01-22 09:55 UTC, cimendes commented on docs/workflows/phylogenetic_construction/clair3_variants.md
> +| clair3_variants_ont | **clair3_model** | String | Model name for variant calling, see latest models: https://github.com/nanoporetech/rerio?tab=readme-ov-file#clair3-models | r941_prom_hac_g360+g422
Instead of linking to nanopore documentation, why not link to the table that you have above with the models already included in the container?

2025-01-22 10:33 UTC, cimendes commented
Tested [here](https://app.terra.bio/#workspaces/theiagen-validations/Theiagen_Mendes_Sandbox/job_history/60b27255-2ca0-4f81-8555-4f85f731f4cc) on haemophilus ONT data. Manual inspection of the the VCF revealed beautifully called variants! I consider this adventure a success! 😄 Great job @Michal-Babins!!! 🌟 

Approving the PR! @sage-wright can do the merge magic!

2025-01-22 10:34 UTC, cimendes submitted a review, later dismissed

2025-01-22 14:15 UTC, sage-wright commented on docs/workflows/phylogenetic_construction/clair3_variants.md
> +| [Phylogenetic Construction](../../workflows_overview/workflows_type.md/#phylogenetic-construction) | [Bacteria](../../workflows_overview/workflows_kingdom.md/#bacteria), [Mycotics](../../workflows_
the current version of this is standalone and doesn't generate a phylogenetic tree so i would argue movng this to a standalone workflow type.

2025-01-22 14:16 UTC, sage-wright commented on docs/workflows/phylogenetic_construction/clair3_variants.md
> +  - Proper handling of long read error profiles
can you add tech details to these tasks as well 🙈 and make these task admonitions

2025-01-22 14:17 UTC, cimendes commented on docs/workflows/phylogenetic_construction/clair3_variants.md
> +| [Phylogenetic Construction](../../workflows_overview/workflows_type.md/#phylogenetic-construction) | [Bacteria](../../workflows_overview/workflows_kingdom.md/#bacteria), [Mycotics](../../workflows_
this is a sister-workflow to snippy_variants so I'm for keeping those two together. Down the road we have plans for a phylogenetic construction workflow that leverages this one.

2025-01-22 14:18 UTC, sage-wright commented on docs/workflows/phylogenetic_construction/clair3_variants.md
> +| [Phylogenetic Construction](../../workflows_overview/workflows_type.md/#phylogenetic-construction) | [Bacteria](../../workflows_overview/workflows_kingdom.md/#bacteria), [Mycotics](../../workflows_
i'm convinced!

2025-01-22 14:18 UTC, cimendes commented on docs/workflows/phylogenetic_construction/clair3_variants.md
> +  - Proper handling of long read error profiles
my bad!!!

2025-01-22 15:14 UTC, Michal-Babins commented
I removed the warning above outputs as well because it was unnecessary after deciding to just provide the final vcf that combines both pileup and alignment variants calls.

2025-01-24 15:16 UTC, sage-wright submitted a review, later dismissed
Inês confirmed functional performance, and I've reviewed the code and documentation. Looks good. ⭐ 

Will merge upon conflict resolution

2025-01-24 15:20 UTC, sage-wright approved these changes

2025-01-24 15:20 UTC, merged