amrfinder & gambit updates
theiagen/public_health_bioinformatics pull request #74
Opened 2023-05-24 14:57 UTC by kapsakcj

Draft for now...

Working on upgrading `amrfinder` task & adding support for all organisms that amrfinder now supports (they have added a few in the last couple of months).

Also ensuring that the gambit task properly sets the `merlin_tag` which is then passed into the `amrfinder` task

So far tests are going well in Terra, as long as GAMBIT can correctly identify the species, amrfinder uses the `--organism` flag for more species.

I'm working on building a validation dataset to test this as well, will post back when it's about ready to share

2023-06-16 17:51 UTC, kapsakcj commented
Need to double check on the imact of changing `merlin_tag` for Klebsiella species. Looks like Kleborate was not run on the K. pneumoniae test samples which is unexpected.

- [ ] figure out which Klebsiella species are appropriate to run through kleborate
- [ ] adjust merlin_magic workflow to accept different species(?) or just the Klebsiella pneumoniae species
- [ ] re-test theiaprok wf on K. pneumoniae samples

2023-07-03 15:58 UTC, kapsakcj commented
Final tests ran successfully after implementing change to `merlin_tag` string output for Shigella sonnei: https://app.terra.bio/#workspaces/theiagen-validations/curtis-sandbox-theiagen-validations/job_history/bed64fa6-7122-4790-b069-2f99559955e0

2023-07-05 20:42 UTC, michellescribner commented
Just a thought: adding the amrfinder_organism input seems like a great way of modifying the merlin_tag if GAMBIT predicts the wrong species. For the qc_check module, I created a similar input called "expected_taxon" that can similarly be used to override the GAMBIT assignment. We might consider consolidating the two inputs since I imagine they would be redundant.

2023-07-07 17:04 UTC, sage-wright commented
Definitely agree with Shelly about consolidating the two variables. The code looks good! Running tests here:
https://app.terra.bio/#workspaces/theiagen-validations/Theiagen_Wright_PHBG_Sandbox/job_history/d5e77768-aa29-4547-8004-1577bb74e46e
https://app.terra.bio/#workspaces/theiagen-validations/Theiagen_Wright_PHBG_Sandbox/job_history/6fac8e00-e3fb-4cc8-8f30-fae919f327e2

2023-07-07 17:06 UTC, sage-wright requested changes
Looks good. I'll approve upon my tests succeeded, the merge conflict resolution (md5sums), and (optionally) the consolidation of amrfinderplus_organism & expected_taxon to avoid redundancy

2023-07-07 17:51 UTC, sage-wright commented on workflows/utilities/wf_merlin_magic.wdl
You'll also need to add a || merlin_tag == "Vibrio cholerae" on line 324

2023-07-07 20:27 UTC, sage-wright commented on workflows/utilities/wf_merlin_magic.wdl
I've done this in my new PR #114

2023-07-12 13:51 UTC, michellescribner commented
Testing completed successfully for:

- TheiaProk_Illumina_PE_PHB: https://app.terra.bio/#workspaces/theiagen-validations/Theiagen_Scribner_Sandbox/job_history/8e21b64a-f38c-4ad4-ba3e-12d069a585fc
- TheiaProk_Illumina_PE_PHB with expected_taxon="clostridiodes_difficile" : https://app.terra.bio/#workspaces/theiagen-validations/Theiagen_Scribner_Sandbox/job_history/3684d93c-5294-490f-80ab-8c2d30c31413
- TheiaProk_FASTA_PHB: https://app.terra.bio/#workspaces/theiagen-validations/Theiagen_Scribner_Sandbox/job_history/50010297-c777-469f-96fa-9165fa482251

2023-07-13 16:40 UTC, sage-wright approved these changes

2023-07-19 13:21 UTC, kevinlibuit approved these changes

2023-07-19 13:21 UTC, merged